name: SonarCloud Analysis
on:
  push:
    branches: [main, jdbc]
  pull_request:
    branches: [main, jdbc]

jobs:
  sonarcloud:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
        with:
          fetch-depth: 0

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'
          cache: maven
          cache-dependency-path: jdbc/pom.xml

      - name: Build project
        if: github.ref == 'refs/heads/jdbc'
        run: mvn clean verify -f jdbc/pom.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}